# Paths
source:      ./app
destination: ./dist

# Setup
name: TITLE
permalink: /blog/:year/:month/:title/
exclude:
 - autoprefixer.yml

# Dependecies
gems:
  - sass
  - compass
  - breakpoint
  - uglifier
  - jekyll-assets
  - jekyll-assets/compass
  - jekyll-sitemap

# Jekyll Assets configuration
# https://github.com/ixti/jekyll-assets
assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/vendor
  js_compressor:  uglifier
  css_compressor: sass
